services:

  api:
    image: pz/api-prod
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PZ_DATABASE_URL=${PZ_DATABASE_URL:?Variable not set}
      - PZ_DEBUG=${PZ_DEBUG:?Variable not set}
      - PZ_CORS_ORIGINS=${PZ_CORS_ORIGINS:?Variable not set}
      - PZ_CORS_HEADERS=${PZ_CORS_HEADERS:?Variable not set}
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://127.0.0.1:8000/ready"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy
    command: uv run fastapi run src/main.py

  db:
    image: mysql:9.7.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD:?Variable not set}
      - MYSQL_DATABASE=${DB_NAME:?Variable not set}
      - MYSQL_USER=${DB_USER:?Variable not set}
      - MYSQL_PASSWORD=${DB_PWD:?Variable not set}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PWD?}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
