services:
  api:
    image: pz/api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: uv run fastapi dev src/main.py --host 0.0.0.0 --port 8000

  db:
    image: mysql:9.7.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD:?Variable not set}
      - MYSQL_DATABASE=${DB_NAME:?Variable not set}
      - MYSQL_USER=${DB_USER:?Variable not set}
      - MYSQL_PASSWORD=${DB_PWD:?Variable not set}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PWD?}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: uv run pytest -v
    env_file:
      - .env

volumes:
  mysql_data: