services:

  api-dev-env:
    image: pz/api-dev
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # wydaje mi się, że podpięcie wszystkich plików w tym wypdaku jest nieszkodliwe, bo to dedykowany dev env
    environment:
      - PZ_DATABASE_URL=${PZ_DATABASE_URL:?Variable not set}
      - PZ_DEBUG=${PZ_DEBUG:?Variable not set}
      - PZ_CORS_ORIGINS=${PZ_CORS_ORIGINS:?Variable not set}
      - PZ_CORS_HEADERS=${PZ_CORS_HEADERS:?Variable not set}
    depends_on:
      db:
        condition: service_healthy
    command: uv run fastapi dev src/main.py --host 0.0.0.0 --port 8000

  db:
    image: mysql:9.7.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD:?Variable not set}
      - MYSQL_DATABASE=${DB_NAME:?Variable not set}
      - MYSQL_USER=${DB_USER:?Variable not set}
      - MYSQL_PASSWORD=${DB_PWD:?Variable not set}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PWD?}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
