from fastapi import HTTPException, status


class ErrorCode:
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    FORBIDDEN = "FORBIDDEN"